version: '2'
services:
  elasticsearch:
    build:
      context: elasticsearch/
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - /opt/alltrade-monitoring/elasticsearch/data:/usr/share/elasticsearch/data
      #- C:/Docker/dockerelkmonitoring/elasticsearch/data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx1g -Xms1g"
      #ES_JAVA_OPTS: "-Xmx250m -Xms250m"
    networks:
      - elk
  logstash:
    build:
      context: logstash/
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "5000:5000"
      - "31311:31311"
    environment:
      LS_JAVA_OPTS: "-Xmx1g -Xms1g"
      #LS_JAVA_OPTS: "-Xmx250m -Xms250m"
    networks:
      - elk
    depends_on:
      - elasticsearch
  kibana:
    build:
      context: kibana/
    volumes:
      - ./kibana/config/:/usr/share/kibana/config:ro
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch
  # elastalert:
  #   build:
  #     context: elastalert/
  #   volumes:
  #     - ./elastalert/config:/opt/config
  #     - ./elastalert/rules:/opt/rules
  #     - /opt/alltrade-monitoring/elastalert/logs:/opt/logs
  #   environment:
  #     - ELASTICSEARCH_HOST: ""
  #     - ELASTICSEARCH_PORT: ""
  #     - ELASTICSEARCH_TLS: False
  #     - ELASTICSEARCH_TLS_VERIFY: False
  #   networks:
  #     - elk 
  #   depends_on:
  #     - elasticsearch
  #     - kibana
  #    links:
  #     - elasticsearch:elasticsearchhost

networks:
  elk:
    driver: bridge
