version: '2'
services:
  redis:
    build:
      context: redis/
    ports:
      - "6379:6379"
    networks:
      - elk
  elasticsearch:
    build:
      context: elasticsearch/
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - /tmp/alltrade-monitoring/elasticsearch/data:/usr/share/elasticsearch/data
      #- C:/Docker/dockerelkmonitoring/elasticsearch/data2:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      #ES_JAVA_OPTS: "-Xmx1g -Xms1g"
      ES_JAVA_OPTS: "-Xmx250m -Xms250m"
    networks:
      - elk
  logstash:
    build:
      context: logstash/
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "5000:5000"
      - "31311:31311"
    environment:
      #LS_JAVA_OPTS: "-Xmx1g -Xms1g"
      LS_JAVA_OPTS: "-Xmx250m -Xms250m"
    networks:
      - elk
    depends_on:
      - elasticsearch
      - redis
  kibana:
    build:
      context: kibana/
    volumes:
      - ./kibana/config/:/usr/share/kibana/config:ro
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch
  curator:
     build:
      context: curator/
     volumes:
       - ./curator/config/:/root/.curator:ro
     networks:
       - elk
     depends_on:
       - elasticsearch
networks:
  elk:
    driver: bridge