version: '2'
services:
  logstash:
    image: r.cfcr.io/gabrielschmith/alltrade-docker-monitoring-logstash:1.0.0
    environment:
      LS_JAVA_OPTS: -Xmx250m -Xms250m
      REDIS_HOST: redis
      REDIS_PASSWORD: pF9tm((MA5>SfyN2
      REDIS_DATATYPE: list
      REDIS_KEY: logstash
      BEATS_PORT: '5000'
      ELASTICSEARCH_HOST: elasticsearch
      ELASTICSEARCH_USER: logstash
      ELASTICSEARCH_PASS: logstash
    stdin_open: true
    volumes:
    - /rancher/alltradeci-elk/config/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
    - /rancher/alltradeci-elk/config/logstash/pipeline:/usr/share/logstash/pipeline:ro
    tty: true
    links:
    - redis:redis
    - elasticsearch:elasticsearch
    labels:
      io.rancher.container.pull_image: always
  logstash-lb:
    image: rancher/lb-service-haproxy:v0.9.1
    ports:
    - 5000:5000/tcp
    - 31311:31311/tcp
    labels:
      io.rancher.container.agent.role: environmentAdmin,agent
      io.rancher.container.agent_service.drain_provider: 'true'
      io.rancher.container.create_agent: 'true'
  elasticsearch:
    image: r.cfcr.io/gabrielschmith/alltrade-docker-monitoring-elasticsearch:1.0.3
    environment:
      ES_JAVA_OPTS: -Xmx1g -Xms1g
    stdin_open: true
    volumes:
    - /rancher/alltradeci-elk/config/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    - /rancher/alltradeci-elk/data/elasticsearch/data:/usr/share/elasticsearch/data
    tty: true
    labels:
      io.rancher.container.pull_image: always
  elasticsearch-lb:
    image: rancher/lb-service-haproxy:v0.9.1
    ports:
    - 9200:9200/tcp
    - 9300:9300/tcp
    labels:
      io.rancher.container.agent.role: environmentAdmin,agent
      io.rancher.container.agent_service.drain_provider: 'true'
      io.rancher.container.create_agent: 'true'
  redis-lb:
    image: rancher/lb-service-haproxy:v0.9.1
    ports:
    - 6379:6379/tcp
    labels:
      io.rancher.container.agent.role: environmentAdmin,agent
      io.rancher.container.agent_service.drain_provider: 'true'
      io.rancher.container.create_agent: 'true'
  kibana-lb:
    image: rancher/lb-service-haproxy:v0.9.1
    ports:
    - 5601:5601/tcp
    labels:
      io.rancher.container.agent.role: environmentAdmin,agent
      io.rancher.container.agent_service.drain_provider: 'true'
      io.rancher.container.create_agent: 'true'
  kibana:
    image: r.cfcr.io/gabrielschmith/alltrade-docker-monitoring-kibana:1.0.0
    stdin_open: true
    volumes:
    - /rancher/alltradeci-elk/config/kibana/config:/usr/share/kibana/config:ro
    tty: true
    links:
    - elasticsearch:elasticsearch
    labels:
      io.rancher.container.pull_image: always
  redis:
    image: redis:4.0.9
    environment:
      REDIS_PASSWORD: pF9tm((MA5>SfyN2
    stdin_open: true
    entrypoint:
    - sh
    - -c
    - exec redis-server /usr/local/etc/redis/redis.conf --requirepass "$$REDIS_PASSWORD"
    volumes:
    - /rancher/alltradeci-elk/config/redis/config/redis.conf:/usr/local/etc/redis/redis.conf:ro
    - /rancher/alltradeci-elk/data/redis/data:/data
    tty: true
    labels:
      io.rancher.container.pull_image: always
