---
## Default Kibana configuration from kibana-docker.
## from https://github.com/elastic/kibana-docker/blob/master/build/kibana/config/kibana.yml
#
server.name: kibana
server.host: "0"
server.cors: true
server.cors.origin: ['*']
server.cors.additionalHeader.origin: ['*']
 
elasticsearch.url: http://elasticsearch:9200

## Custom configuration
#
elasticsearch.username: "kibanaserver"
elasticsearch.password: "kibanaserver"

searchguard.basicauth.enabled: true
searchguard.cookie.password: "Asd12kaskdDa29f850d5b6534ec48a6d7800cbc2b2"
searchguard.basicauth.login.brandimage: https://s3.amazonaws.com/alltrade-files/logo.jpg
searchguard.basicauth.login.title: Por favor faça o login para kibana.
searchguard.basicauth.login.subtitle: Se você esqueceu seu nome de usuário ou senha, por favor, pergunte ao seu administrador de sistema.

sentinl:
  es:
    host: http://elasticsearch
    port: 9200
    timefield: '@timestamp'
    default_index: watcher
    type: sentinl-watcher
    alarm_index: watcher_alarms
    alarm_type: sentinl-alarm
    script_type: sentinl-script
  sentinl:
    history: 20
    results: 50
    scriptResults: 50
  settings:
    email:
      active: true
      user: alltradesystemdevops@gmail.com
      password: all.trade123
      host: smtp.gmail.com
      ssl: true
      timeout: 10000  # mail server connection timeout
    report:
      active: false
      tmp_path: /tmp/
      search_guard: false
      simple_authentication: false
