searchguard:
  dynamic:
    http:
      xff:
        enabled: true
        remoteIpHeader: 'x-forwarded-for'
        proxiesHeader:   'x-forwarded-by'
        internalProxies: '192\.168\.0\.20'
                
    authc:
      basic_internal_auth_domain:
        order: 1
        http_authenticator:
          type: basic
        authentication_backend:
          type: intern
