# https://github.com/elastic/logstash-docker
FROM docker.elastic.co/logstash/logstash-oss:6.1.0

ENV ELASTICSEARCH_HOST=elasticsearch:9200
ENV ELASTICSEARCH_USER=logstash
ENV ELASTICSEARCH_PASS=logstash

# Add your logstash plugins setup here
# Example: RUN logstash-plugin install logstash-filter-json
